#!/bin/bash

BASTION_IP=""
BASTION_USER="ubuntu" 
BASTION_KEY="bastion_key.pem"
RDS_ENDPOINT=""
LOCAL_PORT=3666
RDS_PORT=3306

ssh -i ${BASTION_KEY} -N -L ${LOCAL_PORT}:${RDS_ENDPOINT}:${RDS_PORT} ${BASTION_USER}@${BASTION_IP}
